name: Build on Merge

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure GIT
        run: |
          git config --global user.name 'rtx-inspire'
          git config --global user.email 'inspiringfacts57@gmail.com'

      - name: Create tag
        run: mvn scm:tag

      - name: Update pom to next version
        run:  mvn -U build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}' versions:commit

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update version number"

      - name: Push Changes
        if: github.ref == 'refs/heads/master'
        run: git push origin master